In [37]:
import numpy as np
import pandas as pd


In [36]:
from sklearn.impute import SimpleImputer # for handling missing values 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder # used for encoding categorical data
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler # used for feature selection

In [38]:
dataset = pd.read_csv('DataPreprocessing.csv')
dataset.head()

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes

In [39]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [6]:
X.shape

(10, 3)

In [7]:
y.shape

(10,)

In [8]:
dataset.head()

Region   Age   Income Online Shopper
0   India  49.0  86400.0             No
1  Brazil  32.0  57600.0            Yes
2     USA  35.0  64800.0             No
3  Brazil  43.0  73200.0             No
4     USA  45.0      NaN            Yes

In [15]:
pd.isnull(dataset).head(3)

Region    Age  Income  Online Shopper
0   False  False   False           False
1   False  False   False           False
2   False  False   False           False

In [14]:
pd.isnull(dataset['Income']).head()

0    False
1    False
2    False
3    False
4     True
Name: Income, dtype: bool

In [13]:
dataset.isnull().sum()

Region            0
Age               1
Income            1
Online Shopper    0
dtype: int64

# Handling Missing Data

In [20]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean') 
imputer = imputer.fit(X[:, 1:])
X[:, 1:] = imputer.transform(X[:, 1:])

In [24]:
X

array([['India', 49.0, 86400.0],
       ['Brazil', 32.0, 57600.0],
       ['USA', 35.0, 64800.0],
       ['Brazil', 43.0, 73200.0],
       ['USA', 45.0, 76533.33333333333],
       ['India', 40.0, 69600.0],
       ['Brazil', 43.77777777777778, 62400.0],
       ['India', 53.0, 94800.0],
       ['USA', 55.0, 99600.0],
       ['India', 42.0, 80400.0]], dtype=object)

### Handling of Categorical Data

In [30]:
labelencoder_Y = LabelEncoder()
Y = labelencoder_Y.fit_transform(y)

In [31]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size = 0.3,random_state = 0)

### Feature Scaling

In [33]:
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [34]:
X_train

array([[ 0.8660254 , -0.2029809 ,  0.44897083],
       [-1.15470054, -1.82168936, -1.41706417],
       [-1.15470054,  0.08478949, -1.0242147 ],
       [ 0.8660254 ,  1.5775984 ,  1.62751925],
       [-1.15470054, -0.04111006, -0.14030338],
       [ 0.8660254 ,  0.93011502,  0.94003267],
       [ 0.8660254 , -0.52672259, -0.43494049]])

In [35]:
X_test

array([[ 2.88675135, -1.33607682, -0.82778996],
       [ 2.88675135,  1.90134009,  2.02036872],
       [ 2.88675135,  0.28263164,  0.13250875]])